backend:
  name: git-gateway
  branch: v2

site_url: https://pt-staging.netlify.com
display_url: https://petertait.com
media_folder: static/media
public_folder: /media

collections:
  - name: pages
    label: Pages
    delete: false
    # editor:
    #   preview: false

    files:
      - file: src/pages/home/index.md
        label: Home
        name: home
        fields:
          - {
              label: Template Key,
              name: templateKey,
              widget: hidden,
              default: home-page,
            }
          - {
              label: Page,
              name: page,
              widget: object,
              fields: [{ label: Title, name: title, widget: string }],
            }
          - {
              label: Colors,
              name: colors,
              widget: object,
              fields:
                [
                  {
                    label: Light,
                    name: light,
                    widget: string,
                    default: "white",
                  },
                  { label: Dark, name: dark, widget: string, default: "black" },
                ],
            }
          - {
              label: Hero,
              name: hero,
              widget: object,
              fields:
                [
                  {
                    label: "Shade",
                    name: "shade",
                    widget: "select",
                    options: ["light", "dark"],
                    default: "dark",
                  },
                  { label: Background, name: background, widget: file },
                  { label: Heading, name: heading, widget: string },
                  { label: Subheading, name: subheading, widget: string },
                  {
                    label: Button,
                    name: button,
                    widget: object,
                    fields:
                      [
                        {
                          label: Text,
                          name: text,
                          widget: string,
                          default: Learn more,
                        },
                        { label: Path, name: path, widget: string, default: / },
                      ],
                  },
                ],
            }
          - {
              label: Services,
              name: services,
              widget: object,
              fields:
                [
                  {
                    label: "Shade",
                    name: "shade",
                    widget: "select",
                    options: ["light", "dark"],
                    default: "dark",
                  },
                  { label: Heading, name: heading, widget: string },
                  { label: Text, name: text, widget: string },
                  {
                    label: Service,
                    name: service,
                    widget: list,
                    fields:
                      [
                        { label: Heading, name: heading, widget: string },
                        { label: Text, name: text, widget: string },
                        {
                          label: Image,
                          name: image,
                          widget: file,
                          allow_multiple: false,
                        },
                      ],
                  },
                ],
            }
          - {
              label: Works,
              name: works,
              widget: object,
              fields:
                [
                  {
                    label: "Shade",
                    name: "shade",
                    widget: "select",
                    options: ["light", "dark"],
                    default: "light",
                  },
                  { label: Heading, name: heading, widget: string },
                  { label: Text, name: text, widget: string },
                  {
                    label: Button,
                    name: button,
                    widget: object,
                    fields:
                      [
                        {
                          label: Text,
                          name: text,
                          widget: string,
                          default: "All works",
                        },
                        {
                          label: Path,
                          name: path,
                          widget: string,
                          default: /work,
                        },
                      ],
                  },
                  {
                    label: Work,
                    name: work,
                    widget: list,
                    fields:
                      [
                        {
                          label: Image,
                          name: image,
                          widget: image,
                          allow_multiple: false,
                        },
                        { label: Client, name: client, widget: string },
                        { label: Heading, name: heading, widget: string },
                      ],
                  },
                ],
            }

      - file: src/pages/error/index.md
        label: Error
        name: error
        fields:
          - {
              label: Template Key,
              name: templateKey,
              widget: hidden,
              default: error-page,
            }
          - {
              label: Page,
              name: page,
              widget: object,
              fields:
                [
                  { label: Title, name: title, widget: string },
                  { label: Background, name: background, widget: image },
                ],
            }
          - {
              label: Colors,
              name: colors,
              widget: object,
              fields:
                [
                  {
                    label: Light,
                    name: light,
                    widget: string,
                    default: "white",
                  },
                  { label: Dark, name: dark, widget: string, default: "black" },
                ],
            }
          - {
              label: Hero,
              name: hero,
              widget: object,
              fields:
                [
                  {
                    label: Heading,
                    name: heading,
                    widget: string,
                    required: true,
                    default: empty,
                  },
                  { label: Description, name: description, widget: string },
                  { label: Button Text, name: buttonText, widget: string },
                  { label: Button Path, name: buttonPath, widget: string },
                  {
                    label: "Shade",
                    name: "shade",
                    widget: "select",
                    options: ["light", "dark"],
                    default: "light",
                  },
                ],
            }
