backend:
  name: git-gateway
  branch: master

display_url: https://petertait.com
media_folder: static/media
public_folder: /media
functions: /functions

collections:
  - name: pages
    label: Pages
    delete: false
    editor:
      preview: false

    files:
      - file: src/pages/home/index.md
        label: Home
        name: home
        fields:
          - {
              label: Template Key,
              name: templateKey,
              widget: hidden,
              default: home-page,
            }
          - {
              label: Page,
              name: page,
              widget: object,
              fields:
                [
                  { label: Title, name: title, widget: string },
                  { label: Background, name: background, widget: image },
                ],
            }
          - {
              label: Hero,
              name: hero,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  { label: Description, name: description, widget: text },
                ],
            }
          - {
              label: Introduction,
              name: introduction,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  { label: Description, name: description, widget: text },
                ],
            }
          - {
              label: Approach,
              name: approach,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  { label: Description, name: description, widget: text },
                  {
                    label: Background,
                    name: background,
                    widget: object,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Alt, name: alt, widget: string },
                      ],
                  },
                  {
                    label: Button Text,
                    name: buttonText,
                    widget: string,
                    default: Learn more,
                  },
                  {
                    label: Button Path,
                    name: buttonPath,
                    widget: string,
                    default: /,
                  },
                ],
            }
          - {
              label: Clients,
              name: clients,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  { label: Description, name: description, widget: text },
                  {
                    label: Client,
                    name: client,
                    widget: list,
                    fields:
                      [
                        { label: Name, name: name, widget: string },
                        {
                          label: Image,
                          name: image,
                          widget: file,
                          allow_multiple: false,
                        },
                      ],
                  },
                ],
            }
          - {
              label: Footer,
              name: footer,
              widget: object,
              fields:
                [
                  { label: Quote, name: quote, widget: text },
                  { label: Author, name: author, widget: string },
                  { label: Background, name: background, widget: image },
                ],
            }

      - file: src/pages/error/index.md
        label: Error
        name: error
        fields:
          - {
              label: Template Key,
              name: templateKey,
              widget: hidden,
              default: error-page,
            }
          - {
              label: Page,
              name: page,
              widget: object,
              fields:
                [
                  { label: Title, name: title, widget: string },
                  { label: Background, name: background, widget: image },
                ],
            }
          - {
              label: Hero,
              name: hero,
              widget: object,
              fields:
                [
                  {
                    label: Heading,
                    name: heading,
                    widget: string,
                    required: true,
                    default: empty,
                  },
                  {
                    label: Description,
                    name: description,
                    widget: text,
                    required: true,
                  },
                  { label: Button Text, name: buttonText, widget: string },
                  { label: Button Path, name: buttonPath, widget: string },
                ],
            }
